# XcodeGen Project Configuration for Deets
# Run: xcodegen generate

name: Deets

options:
  bundleIdPrefix: com.sharedeets
  deploymentTarget:
    iOS: 16.0
  developmentLanguage: en
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: 5.9
    DEVELOPMENT_TEAM: # Add your team ID here
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1

targets:
  Deets:
    type: application
    platform: iOS

    sources:
      - path: Deets
        excludes:
          - "**/*.md"
          - "**/Info.plist"
          - "**/PrivacyInfo.xcprivacy"

    resources:
      - path: Deets/Resources
        excludes:
          - "**/*.md"
      - Deets/PrivacyInfo.xcprivacy

    settings:
      base:
        PRODUCT_NAME: Deets
        PRODUCT_BUNDLE_IDENTIFIER: com.sharedeets.app
        INFOPLIST_FILE: Deets/Info.plist
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: Deets/Deets.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_PREVIEWS: YES
        SWIFT_STRICT_CONCURRENCY: complete
        IPHONEOS_DEPLOYMENT_TARGET: 17.0

    dependencies: []

    scheme:
      testTargets:
        - DeetsTests
        - DeetsUITests
      gatherCoverageData: true

  DeetsTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DeetsTests
        excludes:
          - "**/*.md"
    dependencies:
      - target: Deets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sharedeets.app.tests
        IPHONEOS_DEPLOYMENT_TARGET: 17.0

  DeetsUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: DeetsUITests
        excludes:
          - "**/*.md"
    dependencies:
      - target: Deets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sharedeets.app.uitests
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
